package com.example.foodfridge.common

data class Category(val id: Int, val name: String)
data class Ingredient(val ingredient_id: Int, val ingredient_name: String, val ingredient_type_code: Int)
object PantryCategory {
//    val pantryCategory = arrayOf("Carb", "Vegetable", "Meat", "Fruit", "Dairy", "Seasoning", "Seafood", "Pantry");
    val pantryCategory = listOf(
        Category(1, "My pantry"),
        Category(2, "Meat"),
        Category(3, "Seafood"),
        Category(4, "Dairy and Alternatives"),
        Category(5, "Paste and Sauces"),
        Category(6, "Cereals and Pulses"),
        Category(7, "Carbohydrate"),
        Category(8, "Vegetable"),
        Category(9, "Fruit"),
        Category(10, "Spices and Seasonings"),
        Category(11, "Sugar and Sugar Products"),
        Category(12, "Other Ingredients"),
    )
}

object PantryIngredient {
    val pantryIngredient = listOf(
        Ingredient(1, "Chicken", 2),
        Ingredient(2, "Beef", 2),
        Ingredient(3, "Pork", 2),
        Ingredient(4, "Turkey", 2),
        Ingredient(5, "Lamb", 2),
        Ingredient(6, "Tofu", 2),
        Ingredient(7, "Quinoa", 2),
        Ingredient(8, "Salmon", 3),
        Ingredient(9, "Cod", 3),
        Ingredient(10, "Shrimp", 3),
        Ingredient(11, "Tuna", 3),
        Ingredient(12, "Lobster", 3),
        Ingredient(13, "Crab", 3),
        Ingredient(14, "Mussels", 3),
        Ingredient(15, "Milk", 4),
        Ingredient(16, "Yogurt", 4),
        Ingredient(17, "Cheese", 4),
        Ingredient(18, "Almond Milk", 4),
        Ingredient(19, "Soy Yogurt", 4),
        Ingredient(20, "Soy sauce", 5),
        Ingredient(21, "Tomato Sauce", 5),
        Ingredient(22, "Pesto", 5),
        Ingredient(23, "Barbecue Sauce", 5),
        Ingredient(24, "Hummus", 5),
        Ingredient(25, "Cereal", 6),
        Ingredient(26, "Lentils", 6),
        Ingredient(27, "Chickpeas", 6),
        Ingredient(28, "Quinoa", 6),
        Ingredient(29, "Oats", 6),
        Ingredient(30, "Pasta", 7),
        Ingredient(31, "Rice", 7),
        Ingredient(32, "Bread", 7),
        Ingredient(33, "Potatoes", 7),
        Ingredient(34, "Quinoa", 7),
        Ingredient(35, "Couscous", 7),
        Ingredient(36, "Sweet Potatoes", 7),
        Ingredient(37, "Tomato", 8),
        Ingredient(38, "Broccoli", 8),
        Ingredient(39, "Carrot", 8),
        Ingredient(40, "Spinach", 8),
        Ingredient(41, "Bell Pepper", 8),
        Ingredient(42, "Cucumber", 8),
        Ingredient(43, "Zucchini", 8),
        Ingredient(44, "Onion", 8),
        Ingredient(45, "Mushroom", 8),
        Ingredient(46, "Kale", 8),
        Ingredient(47, "Banana", 9),
        Ingredient(48, "Apple", 9),
        Ingredient(49, "Orange", 9),
        Ingredient(50, "Strawberry", 9),
        Ingredient(51, "Mango", 9),
        Ingredient(52, "Pineapple", 9),
        Ingredient(53, "Grapes", 9),
        Ingredient(54, "Watermelon", 9),
        Ingredient(55, "Kiwi", 9),
        Ingredient(56, "Blueberries", 9),
        Ingredient(57, "Chilli pepper", 10),
        Ingredient(58, "Cumin", 10),
        Ingredient(59, "Paprika", 10),
        Ingredient(60, "Garlic powder", 10),
        Ingredient(61, "Oregano", 10),
        Ingredient(62, "Sugar", 11),
        Ingredient(63, "Honey", 11),
        Ingredient(64, "Maple Syrup", 11),
        Ingredient(65, "Agave Nectar", 11),
        Ingredient(66, "Brown Sugar", 11),
        Ingredient(67, "Coconut Oil", 12),
        Ingredient(68, "Peanut Butter", 12),
        Ingredient(69, "Sesame Seeds", 12),
        Ingredient(70, "Balsamic Vinegar", 12),
        Ingredient(71, "Avocado", 12)
    )
}